```{r}{Only Run this if you need to install packages for the first time}
remotes::install_github(repo="phillipbvetter/ctsmTMB", dependencies=TRUE) # reference: https://phillipbvetter.github.io/ctsmTMB/index.html
require(tidyverse)
require(patchwork)
require(rmarkdown)
```

```{r}{Only Run this if you want to update packages}
remotes::install_github(repo="phillipbvetter/ctsmTMB", dependencies=TRUE) # reference: https://phillipbvetter.github.io/ctsmTMB/index.html
update.packages(ask = F) # update all R packages
```

```{r}{Main code part}
rm(list = ls())

setwd(dirname(rstudioapi::documentPath()))
Rfolder = "ctsm"
csv_folder = "csv/"
if (!dir.exists(Rfolder)){
  dir.create(Rfolder)
}
library(tidyverse)
library(ctsmTMB)
library(patchwork)

AIC <- function(model, fit){
return( 2*(nrow(model$getParameters()) + fit$nll) )
}

RMSE <- function(pred){
  sqrt(mean(c(pred$observations$yT4 - pred$observations$yT4.data, pred$observations$yT3 - pred$observations$yT3.data, pred$observations$yT2 - pred$observations$yT2.data)^2))
}

model_estimate <- function(model, name){
  fit <- model$estimate(df, method = "ekf", ode.solver = "rk4")
  return(fit)
}

model_predict <- function(model, df){
  pred <- model$predict(df, ode.solver = "rk4")
  return(pred)
}

model_fixed_mu <- function(){
  model <- ctsmTMB$new()
  model$addSystem(
    dT4 ~ (k4*(mu - T4) + P4)*dt + sigma_x4*dw4,
    dT3 ~ (k*(T4 - T3) + P3)*dt + sigma_x*dw3,
    dT2 ~ (k*(T3 - T2) + P2)*dt + sigma_x*dw2
  )
  model$addInput(mu)
  model$addObs(
    yT4 ~ T4,
    yT3 ~ T3,
    yT2 ~ T2
  )
  model$setVariance(
    yT4 ~ sigma_y^2,
    yT3 ~ sigma_y^2,
    yT2 ~ sigma_y^2
  )
  model$setAlgebraics(
    k ~ exp(logk),
    k4 ~ exp(logk4),
    sigma_x ~ exp(logsigma_x), # shall be positive
    sigma_x4 ~ exp(logsigma_x4), # shall be positive
    P4 ~ P40 - P_loss*(T4 - 25),
    P3 ~ P30 - P_loss*(T3 - 25),
    P2 ~ P20 - P_loss*(T2 - 25)
  )
  model$setParameter(
    logk = c(1, -5, 7),
    logk4 = c(1, -5, 7),
    P40 = c(10, -5000, 5000),
    P30 = c(10, -5000, 5000),
    P20 = c(10, -5000, 5000),
    P_loss = c(10, -5000, 5000),
    logsigma_x = c(0, -5, 10),
    logsigma_x4 = c(0, -5, 10),
    sigma_y = 0.05 # I just picked a random number +-0.1 = 2 * sd
    # sigma_y = c(1, 1E-5, 10)
  )
  model$setInitialState(list(c(df$yT4[1], df$yT3[1], df$yT2[1]), 1 * diag(3)))
  return(model)
}

model_fixed_mu_yT1 <- function(){
  model <- ctsmTMB$new()
  model$addSystem(
    dT4 ~ (k4*(mu - T4) + P4)*dt + sigma_x4*dw4,
    dT3 ~ (k*(T4 - T3) + P3)*dt + sigma_x*dw3,
    dT2 ~ (k*(T3 - T2) + P2)*dt + sigma_x*dw2
  )
  model$addInput(mu, yT1)
  model$addObs(
    yT4 ~ T4,
    yT3 ~ T3,
    yT2 ~ T2
  )
  model$setVariance(
    yT4 ~ sigma_y^2,
    yT3 ~ sigma_y^2,
    yT2 ~ sigma_y^2
  )
  model$setAlgebraics(
    k ~ exp(logk),
    k4 ~ exp(logk4),
    sigma_x ~ exp(logsigma_x), # shall be positive
    sigma_x4 ~ exp(logsigma_x4), # shall be positive
    P4 ~ P40 - P_loss*(T4 - yT1),
    P3 ~ P30 - P_loss*(T3 - yT1),
    P2 ~ P20 - P_loss*(T2 - yT1)
  )
  model$setParameter(
    logk = c(1, -5, 7),
    logk4 = c(1, -5, 7),
    P40 = c(10, -5000, 5000),
    P30 = c(10, -5000, 5000),
    P20 = c(10, -5000, 5000),
    P_loss = c(10, -5000, 5000),
    logsigma_x = c(0, -5, 10),
    logsigma_x4 = c(0, -5, 10),
    sigma_y = 0.05 # I just picked a random number +-0.1 = 2 * sd
    # sigma_y = c(1, 1E-5, 10)
  )
  model$setInitialState(list(c(df$yT4[1], df$yT3[1], df$yT2[1]), 1 * diag(3)))
  return(model)
}

model_dynamic_mu <- function(){
  model <- ctsmTMB$new()
  model$addSystem(
    dT4 ~ (k4*( (q_circ*T0 + q_des*alpha*T_des)/(q_circ + q_des) - T4) + P4)*dt + sigma_x4*dw4,
    dT3 ~ (k*(T4 - T3) + P3)*dt + sigma_x*dw3,
    dT2 ~ (k*(T3 - T2) + P2)*dt + sigma_x*dw2
  )
  model$addInput(q_circ, q_des, T0, T_des)
  model$addObs(
    yT4 ~ T4,
    yT3 ~ T3,
    yT2 ~ T2
  )
  model$setVariance(
    yT4 ~ sigma_y^2,
    yT3 ~ sigma_y^2,
    yT2 ~ sigma_y^2
  )
  model$setAlgebraics(
    k ~ exp(logk),
    k4 ~ exp(logk4),
    sigma_x ~ exp(logsigma_x), # shall be positive
    sigma_x4 ~ exp(logsigma_x4), # shall be positive
    P4 ~ P40 - P_loss*(T4 - 25),
    P3 ~ P30 - P_loss*(T3 - 25),
    P2 ~ P20 - P_loss*(T2 - 25)
  )
  model$setParameter(
    logk = c(1, -5, 7),
    logk4 = c(1, -5, 7),
    alpha = c(0, -10, 10),
    P40 = c(10, -5000, 5000),
    P30 = c(10, -5000, 5000),
    P20 = c(10, -5000, 5000),
    P_loss = c(10, -5000, 5000),
    logsigma_x = c(0, -5, 10),
    logsigma_x4 = c(0, -5, 10),
    sigma_y = 0.05 # I just picked a random number +-0.1 = 2 * sd
    # sigma_y = c(1, 1E-5, 10)
  )
  model$setInitialState(list(c(df$yT4[1], df$yT3[1], df$yT2[1]), 1 * diag(3)))
  return(model)
}

model_dynamic_mu_no_k4_sigma_x4 <- function(){
  model <- ctsmTMB$new()
  model$addSystem(
    dT4 ~ (k*( (q_circ*T0 + q_des*alpha*T_des)/(q_circ + q_des) - T4) + P4)*dt + sigma_x*dw4,
    dT3 ~ (k*(T4 - T3) + P3)*dt + sigma_x*dw3,
    dT2 ~ (k*(T3 - T2) + P2)*dt + sigma_x*dw2
  )
  model$addInput(q_circ, q_des, T0, T_des)
  model$addObs(
    yT4 ~ T4,
    yT3 ~ T3,
    yT2 ~ T2
  )
  model$setVariance(
    yT4 ~ sigma_y^2,
    yT3 ~ sigma_y^2,
    yT2 ~ sigma_y^2
  )
  model$setAlgebraics(
    k ~ exp(logk),
    sigma_x ~ exp(logsigma_x), # shall be positive
    P4 ~ P40 - P_loss*(T4 - 25),
    P3 ~ P30 - P_loss*(T3 - 25),
    P2 ~ P20 - P_loss*(T2 - 25)
  )
  model$setParameter(
    logk = c(1, -5, 7),
    alpha = c(0, -10, 10),
    P40 = c(10, -5000, 5000),
    P30 = c(10, -5000, 5000),
    P20 = c(10, -5000, 5000),
    P_loss = c(10, -5000, 5000),
    logsigma_x = c(0, -5, 10),
    sigma_y = 0.05 # I just picked a random number +-0.1 = 2 * sd
    # sigma_y = c(1, 1E-5, 10)
  )
  
  model$setInitialState(list(c(df$yT4[1], df$yT3[1], df$yT2[1]), 1 * diag(3)))
  return(model)
}

model_dynamic_mu_no_P_loss <- function(){
  model <- ctsmTMB$new()
  model$addSystem(
    dT4 ~ (k4*( (q_circ*T0 + q_des*alpha*T_des)/(q_circ + q_des) - T4) + P4)*dt + sigma_x4*dw4,
    dT3 ~ (k*(T4 - T3) + P3)*dt + sigma_x*dw3,
    dT2 ~ (k*(T3 - T2) + P2)*dt + sigma_x*dw2
  )
  model$addInput(q_circ, q_des, T0, T_des)
  model$addObs(
    yT4 ~ T4,
    yT3 ~ T3,
    yT2 ~ T2
  )
  model$setVariance(
    yT4 ~ sigma_y^2,
    yT3 ~ sigma_y^2,
    yT2 ~ sigma_y^2
  )
  model$setAlgebraics(
    k ~ exp(logk),
    k4 ~ exp(logk4),
    sigma_x ~ exp(logsigma_x), # shall be positive
    sigma_x4 ~ exp(logsigma_x4), # shall be positive
    P4 ~ P40,
    P3 ~ P30,
    P2 ~ P20
  )
  model$setParameter(
    logk = c(1, -5, 7),
    logk4 = c(1, -5, 7),
    alpha = c(0, -10, 10),
    P40 = c(10, -5000, 5000),
    P30 = c(10, -5000, 5000),
    P20 = c(10, -5000, 5000),
    logsigma_x = c(0, -5, 10),
    logsigma_x4 = c(0, -5, 10),
    sigma_y = 0.05 # I just picked a random number +-0.1 = 2 * sd
    # sigma_y = c(1, 1E-5, 10)
  )
  model$setInitialState(list(c(df$yT4[1], df$yT3[1], df$yT2[1]), 1 * diag(3)))
  return(model)
}

model_dynamic_mu_no_k4_sigma_x4_P_loss <- function(){
  model <- ctsmTMB$new()
  model$addSystem(
    dT4 ~ (k*( (q_circ*T0 + q_des*alpha*T_des)/(q_circ + q_des) - T4) + P4)*dt + sigma_x*dw4,
    dT3 ~ (k*(T4 - T3) + P3)*dt + sigma_x*dw3,
    dT2 ~ (k*(T3 - T2) + P2)*dt + sigma_x*dw2
  )
  model$addInput(q_circ, q_des, T0, T_des)
  model$addObs(
    yT4 ~ T4,
    yT3 ~ T3,
    yT2 ~ T2
  )
  model$setVariance(
    yT4 ~ sigma_y^2,
    yT3 ~ sigma_y^2,
    yT2 ~ sigma_y^2
  )
  model$setAlgebraics(
    k ~ exp(logk),
    sigma_x ~ exp(logsigma_x), # shall be positive
    P4 ~ P40,
    P3 ~ P30,
    P2 ~ P20
  )
  model$setParameter(
    logk = c(1, -5, 7),
    alpha = c(0, -10, 10),
    P40 = c(10, -5000, 5000),
    P30 = c(10, -5000, 5000),
    P20 = c(10, -5000, 5000),
    logsigma_x = c(0, -5, 10),
    sigma_y = 0.05 # I just picked a random number +-0.1 = 2 * sd
    # sigma_y = c(1, 1E-5, 10)
  )
  model$setInitialState(list(c(df$yT4[1], df$yT3[1], df$yT2[1]), 1 * diag(3)))
  return(model)
}

model_dynamic_mu_yT1 <- function(){
  model <- ctsmTMB$new()
  model$addSystem(
    dT4 ~ (k4*( (q_circ*T0 + q_des*alpha*T_des)/(q_circ + q_des) - T4) + P4)*dt + sigma_x4*dw4,
    dT3 ~ (k*(T4 - T3) + P3)*dt + sigma_x*dw3,
    dT2 ~ (k*(T3 - T2) + P2)*dt + sigma_x*dw2
  )
  model$addInput(q_circ, q_des, T0, T_des, yT1)
  model$addObs(
    yT4 ~ T4,
    yT3 ~ T3,
    yT2 ~ T2
  )
  model$setVariance(
    yT4 ~ sigma_y^2,
    yT3 ~ sigma_y^2,
    yT2 ~ sigma_y^2
  )
  model$setAlgebraics(
    k ~ exp(logk),
    k4 ~ exp(logk4),
    sigma_x ~ exp(logsigma_x), # shall be positive
    sigma_x4 ~ exp(logsigma_x4), # shall be positive
    P4 ~ P40 - P_loss*(T4 - yT1),
    P3 ~ P30 - P_loss*(T3 - yT1),
    P2 ~ P20 - P_loss*(T2 - yT1)
  )
  model$setParameter(
    logk = c(1, -5, 7),
    logk4 = c(1, -5, 7),
    alpha = c(0, -10, 10),
    P40 = c(10, -5000, 5000),
    P30 = c(10, -5000, 5000),
    P20 = c(10, -5000, 5000),
    P_loss = c(10, -5000, 5000),
    logsigma_x = c(0, -5, 10),
    logsigma_x4 = c(0, -5, 10),
    sigma_y = 0.05 # I just picked a random number +-0.1 = 2 * sd
    # sigma_y = c(1, 1E-5, 10)
  )
  model$setInitialState(list(c(df$yT4[1], df$yT3[1], df$yT2[1]), 1 * diag(3)))
  return(model)
}

add_to_table <- function(){
  ls_AIC <<- c(ls_AIC, AIC(model, fit))
  ls_RMSE <<- c(ls_RMSE, RMSE(pred))
  ls_nll <<- c(ls_nll, fit$nll)
  ls_df <<- c(ls_df, nrow(model$getParameters()))
}

model_fit_and_predict <- function(model, df, name){
  fit <<- model_estimate(model, name)
  pred <<- model$predict(df, ode.solver = "rk4")
  model_param_save()
  add_to_table()
  model_plot()
}

model_param_save <- function(){
  sink(file = output_file, append = T)
  print(name)
  print(model_name)
  print(fit)
  sink(file = NULL)
}

model_plot <- function(){
  x_lim = NULL
  y_lim = NULL
  
  pvar4 <<- ggplot() +
  geom_point(aes(y = pred$states$var.T4, x = pred$observations$t.j), size = 0.2) +
  xlab("Time [hours]") +
  ylab("Variance for T4 prediction") +
  theme_minimal() + 
  theme_bw(base_size=base_size) #+
  # coord_cartesian(xlim = x_lim, ylim = y_lim)

  pvar3 <<- ggplot() +
    geom_point(aes(y = pred$states$var.T3, x = pred$observations$t.j), size = 0.2) +
    xlab("Time [hours]") +
    ylab("Variance for T3 prediction") +
    theme_minimal() + 
    theme_bw(base_size=base_size) #+
    # coord_cartesian(xlim = x_lim, ylim = y_lim)
  
  pvar2 <<- ggplot() +
    geom_point(aes(y = pred$states$var.T2, x = pred$observations$t.j), size = 0.2) +
    xlab("Time [hours]") +
    ylab("Variance for T2 prediction") +
    theme_minimal() + 
    theme_bw(base_size=base_size) #+
    # coord_cartesian(xlim = x_lim, ylim = y_lim)
  
  p4 <<- ggplot(data = pred$observations) +
    geom_point(aes(y = yT4.data, x = t.j, color = "Data"), size = 0.2) +
    geom_line(aes(y = yT4, x = t.j, color = "Prediction")) +
    # geom_line(aes(y = (df$q_circ*df$T0 + df$q_des*fit$par.fixed["alpha"]*df$T_des)/(df$q_circ + df$q_des), x = t.j, color = "T_avg_alpha"), linewidth = 0.5) +
    geom_ribbon(aes(ymin = yT4 - 2 * sqrt(pred$states$var.T4),
                    ymax = yT4 + 2 * sqrt(pred$states$var.T4),
                    x = t.j, fill = "Prediction interval"), alpha = 0.2) +
    xlab("Time [hours]") +
    ylab("T4 Temperature [°C]") +
    coord_cartesian(xlim = x_lim, ylim = y_lim) +
    scale_color_manual(values = c("Data" = "black", "Prediction" = "red", "T_avg_alpha" = "green")) +
    # scale_color_manual(values = c("Data" = "black", "Prediction" = "red", "mu" = "green")) +
    scale_fill_manual(values = c("Prediction interval" = "blue")) +
    theme_minimal() + 
    theme_bw(base_size=base_size)
  
  
  p3 <<- ggplot(data = pred$observations) +
    geom_point(aes(y = yT3.data, x = t.j, color = "Data"), size = 0.2) +
    geom_line(aes(y = yT3, x = t.j, color = "Prediction")) +
    # geom_line(aes(y = df$mu, x = t.j, color = "mu"), linewidth = 0.5) +
    geom_ribbon(aes(ymin = yT3 - 2 * sqrt(pred$states$var.T3),
                    ymax = yT3 + 2 * sqrt(pred$states$var.T3),
                    x = t.j, fill = "Prediction interval"), alpha = 0.2) +
    xlab("Time [hours]") +
    ylab("T3 Temperature [°C]") +
    coord_cartesian(xlim = x_lim, ylim = y_lim) +
    scale_color_manual(values = c("Data" = "black", "Prediction" = "red")) +
    # scale_color_manual(values = c("Data" = "black", "Prediction" = "red", "mu" = "green")) +
    scale_fill_manual(values = c("Prediction interval" = "blue")) +
    theme_minimal() + 
    theme_bw(base_size=base_size)
  
  p2 <<- ggplot(data = pred$observations) +
    geom_point(aes(y = yT2.data, x = t.j, color = "Data"), size = 0.2) +
    geom_line(aes(y = yT2, x = t.j, color = "Prediction")) +
    # geom_line(aes(y = df$mu, x = t.j, color = "mu"), linewidth = 0.5) +
    geom_ribbon(aes(ymin = yT2 - 2 * sqrt(pred$states$var.T2),
                    ymax = yT2 + 2 * sqrt(pred$states$var.T2),
                    x = t.j, fill = "Prediction interval"), alpha = 0.2) +
    xlab("Time [hours]") +
    ylab("T2 Temperature [°C]") +
    coord_cartesian(xlim = x_lim, ylim = y_lim) +
    scale_color_manual(values = c("Data" = "black", "Prediction" = "red")) +
    # scale_color_manual(values = c("Data" = "black", "Prediction" = "red", "mu" = "green")) +
    scale_fill_manual(values = c("Prediction interval" = "blue")) +
    theme_minimal() + 
    theme_bw(base_size=base_size)
  
  pqc <<- ggplot(df) +
    geom_point(aes(y = q_circ, x = t), size = 0.2) +
    xlab("Time [hours]") +
    ylab("q_circ [m^3/s]") + 
    theme_bw(base_size=base_size)#+
    # coord_cartesian(xlim = x_lim, ylim = y_lim)
  
  pqd <<- ggplot(df) +
    geom_point(aes(y = q_des, x = t), size = 0.2) +
    xlab("Time [hours]") +
    ylab("q_des [m^3/s]") + 
    theme_bw(base_size=base_size) #+
    # coord_cartesian(xlim = x_lim, ylim = y_lim)
  
  model_plot_save()
}

model_plot_save <- function(){
  # save plots
  gg + pqc + pqd + plot_layout(ncol = 1)
  ggsave(sprintf("%s/%s %s data.png", Rfolder, model_name, name), width = 30, height = 17, units = "cm", dpi = 600)
  
  if (model_name == "yT4"){
    p3 + p2 + plot_layout(ncol = 1)
    ggsave(sprintf("%s/%s %s fit.png", Rfolder, model_name, name), width = 30, height = 17, units = "cm", dpi = 600)
  } else {
    p4 + p3 + p2 + plot_layout(ncol = 1)
    ggsave(sprintf("%s/%s %s fit.png", Rfolder, model_name, name), width = 30, height = 17, units = "cm", dpi = 600)
  }
  # pvar3 + pvar2 + plot_layout(ncol = 1)
  # ggsave(sprintf("%s/%s %s var.png", Rfolder, model_name, name), width = 30, height = 17, units = "cm", dpi = 600)
  
  # Residuals
  if (model_name == "yT4"){
    plot(fit, print.plot = 1)
    ggsave(sprintf("%s/%s %s T3.png", Rfolder, model_name, name), bg = "white",width = 30, height = 17, units = "cm", dpi = 600)
    plot(fit, print.plot = 2)
    ggsave(sprintf("%s/%s %s T2.png", Rfolder, model_name, name), bg = "white", width = 30, height = 17, units = "cm", dpi = 600)
  } else {
    plot(fit, print.plot = 1)
    ggsave(sprintf("%s/%s %s T4.png", Rfolder, model_name, name), bg = "white",width = 30, height = 17, units = "cm", dpi = 600)
    plot(fit, print.plot = 2)
    ggsave(sprintf("%s/%s %s T3.png", Rfolder, model_name, name), bg = "white", width = 30, height = 17, units = "cm", dpi = 600)
    plot(fit, print.plot = 3)
    ggsave(sprintf("%s/%s %s T2.png", Rfolder, model_name, name), bg = "white", width = 30, height = 17, units = "cm", dpi = 600)
    
  }
  
}

load_data <- function(arg){
  if (arg == "May") {
    ##----2024_May----##
    
    # Long
    a <- c("1", "2024-05-27 14:00:00", "2024-06-01 00:00:00")
    csv_name <- "2024_May.csv"
  } else if (arg == "May steady") {
    ##----2024_May----##
    
    # Long
    a <- c("3", "2024-05-28 17:00:00", "2024-05-29 07:00:00")
    csv_name <- "2024_May.csv"
  } else if (arg == "June short") {
    ##----2024_June----##
    
    # Another short
    # a <- c("1", "2024-06-25 15:42:00", "2024-06-26 08:15:00")
    
    # Short
    a <- c("1", "2024-06-27 20:00:00", "2024-06-28 00:00:00")
    # a <- c("1", "2024-06-25 16:00:00", "2024-06-27 21:51:00")
    # a <- c("1", "2024-06-25 16:00:00", "2024-06-27 21:51:00")
    csv_name <- "2024_June.csv"
  } else if (arg == "June long") {
    ##----2024_June----##
    
    # Another short
    # a <- c("1", "2024-06-25 15:42:00", "2024-06-26 08:15:00")
    
    # Long
    a <- c("1", "2024-06-25 10:00:00", "2024-06-29 00:00:00")
    csv_name <- "2024_June.csv"
  } else if (arg == "March"){
    ##----2025_March----##
    # Short
    # a <- c("1", "2025-03-05 11:00:00", "2025-03-05 15:00:00")
    
    # March whole (broken)
    a <- c("1", "2025-03-02 12:00:00", "2025-03-15 00:00:00")

    csv_name <- "2025_March.csv"
  } else if (arg == "March 1") {
    ##----2025_March----##
    # March 1
    a <- c("1", "2025-03-04 09:08:00", "2025-03-04 13:00:00")
    csv_name <- "2025_March.csv"
  } else if (arg == "March 2") {
    ##----2025_March----##
    # March 1
    a <- c("1", "2025-03-05 10:35:00", "2025-03-05 15:30:00")
    csv_name <- "2025_March.csv"
  } else if (arg == "March 3") {
    ##----2025_March----##
    # March 1
    # a <- c("1", "2025-03-06 08:00:00", "2025-03-07 00:00:00")
    a <- c("1", "2025-03-06 09:08:00", "2025-03-06 15:16:00")
    csv_name <- "2025_March.csv"
  }
  else {
    stop("Invalid argument. Use 'May', 'June' or 'March'.")
  }


  csv <- read_csv(paste(csv_folder, csv_name, sep=""), show_col_types = FALSE)
  
  region_table <- tribble(
    ~region, ~t_start, ~t_end,
    a[1], a[2], a[3]
  ) |>
  mutate(
    t_start = as.POSIXct(t_start, tz = "UTC"),
    t_end = as.POSIXct(t_end, tz = "UTC")
  )
  
  tmp <- region_table

  df_tidy <- csv |>
    select(time, metric, value) |>
    mutate(metric = case_when(
      metric == "T_abs_out_1 - [°C]" ~ "yT5",
      metric == "T_pack_top_2 - [°C]" ~ "yT4",
      metric == "T_pack_mid_3 - [°C]" ~ "yT3",
      metric == "T_pack_bot_4 - [°C]" ~ "yT2",
      metric == "T_abs_tank_5 - [°C]" ~ "yT1",
      metric == "A010_BT01 - [°C]" ~ "yT0",
      .default = metric)
    ) |>
    filter(time >= tmp$t_start & time <= tmp$t_end) |>
    mutate(t = as.numeric(time - time[1])) |>
    arrange(time, metric) |>
    relocate(time, t, metric, value)
  
  df <- df_tidy |>
    pivot_wider(names_from = metric, values_from = value) |>
    relocate(yT0, yT1, yT2, yT3, yT4, yT5, .after = t) |>
    rename(
      `q_circ+q_des` = `A010_BF01 - [m³/h]`,
      `q_circ` = `A010_BF02 - [m³/h]`,
      `T_des` = `A050_BT01 - [°C]`, # Desorber process tank
      `T0` = `yT0`
    ) |> 
    mutate(q_des = `q_circ+q_des` - `q_circ`, .after = `q_circ`) |>
    filter(q_des > 0.0) |>
    mutate(across(c(T0, yT1, yT2, yT3, yT4, yT5, q_circ, q_des, T_des), ~ if_else(q_des <= 0.0, NA, .))) |>  # set negative q_des row NA
    select(time, t, T0, yT1, yT2, yT3, yT4, yT5, q_circ, q_des, T_des)
  
  # Convert time from seconds to hours
  df$t <- df$t/3600
  
    # linear interpolate the missing values
  if (arg == "March 1"){
    df <- df |>
      filter(q_circ > 3.0) # filter out one outlier
      missing_time <- seq(as.POSIXct("2025-03-04 12:11:13", tz = "UTC"), as.POSIXct("2025-03-04 12:17:33", tz = "UTC"), 20)
      missing_df <- tibble(time = missing_time, t = missing_time - as.POSIXct("2025-03-04 09:08:08 UTC", tz = "UTC"),T0 = NA, yT1 = NA, yT2 = NA, yT3 = NA, yT4 = seq(43.4, 39.2, length.out = length(missing_time)), yT5 = NA, q_circ = seq(3.58, 3.57, length.out = length(missing_time)), q_des = seq(0.100, 0.0388, length.out = length(missing_time)), T_des = NA)
      
      rbind(df, missing_df) |> arrange(t) -> df
  } else if (arg == "March 3"){
    df <- df |>
        mutate(mu = case_when(
          time >= datetime("2025-03-06 09:08:00") & time < datetime("2025-03-06 11:11:00") ~ 32,
          time >= datetime("2025-03-06 11:11:00") & time < datetime("2025-03-06 13:11:00") ~ 30.2,
          time >= datetime("2025-03-06 13:11:00") & time < datetime("2025-03-06 15:16:00") ~ 33,
          .default = NA)
        ) 
  } else if (arg == "June long" | arg == "June short"){
    df <- df |>
        mutate(mu = case_when(
          time >= datetime("2024-06-25 10:00:00") & time < datetime("2024-06-25 15:46:30") ~ 45,
          time >= datetime("2024-06-25 15:46:30") & time < datetime("2024-06-26 08:23:00") ~ 30,
          time >= datetime("2024-06-26 08:23:00") & time < datetime("2024-06-27 21:51:00") ~ 45,
          time >= datetime("2024-06-27 21:51:00") & time < datetime("2024-06-29 00:00:00") ~ 30,
          .default = NA)
        ) 
  }
  return(df)
}

datetime <- function(arg){
  return(as.POSIXct(arg, tz = "UTC"))
}


base_size = 15

# all_model_names <- c("fixed_mu", 
#                  "fixed_mu_yT1", 
#                  "dynamic_mu", 
#                  "dynamic_mu_no_k4_sigma_x4", 
#                  "dynamic_mu_no_P_loss",
#                  "dynamic_mu_no_k4_sigma_x4_P_loss")
# names <- c("May","June short", "June long", "March 1", "March 2", "March 3")

for (sample_idx in 1:2) {

ls_AIC <- c()
ls_RMSE <- c()
ls_nll <- c()
ls_df <- c()
param_table <- c()
  
if (sample_idx == 1){
  model_names <- c("fixed_mu", 
                  "fixed_mu_yT1"
  )

  name <- c("June short")
} else if (sample_idx == 2){
  model_names <- c("dynamic_mu", 
                  "dynamic_mu_no_k4_sigma_x4", 
                  "dynamic_mu_no_P_loss",
                  "dynamic_mu_no_k4_sigma_x4_P_loss",
                  "dynamic_mu_yT1")
  name <- c("March 3")
}

for (model_name in model_names)
{
output_file <- sprintf("%s/%s %s Routput.txt", Rfolder, model_name, name)

sink(file = output_file)
print("START!")
sink(file = NULL)

print(name)
print(model_name)

# Load data
df <- load_data(name)
# x_lim <- c(7,22)
# Create orginal data plot
if (name == "June short" | name == "June long"){
gg <- ggplot(df, aes(x = time)) +
  geom_point(aes(y = yT4, color = "T4"), size = 0.2) +
  geom_point(aes(y = yT3, color = "T3"), size = 0.2) +
  geom_point(aes(y = yT2, color = "T2"), size = 0.2) +
  geom_point(aes(y = mu, color = "mu"), size = 0.2) +
  labs(title = sprintf("Original Data\nFrom %s to %s", head(df$time,1), tail(df$time,1)), color = 'Probes') +
  ylab("Temperature [ceisius]") + 
  theme_minimal() + 
  theme_bw(base_size=base_size) # +
  # coord_cartesian(xlim = x_lim)
} else {
gg <- ggplot(df, aes(x = time)) +
  geom_point(aes(y = yT4, color = "T4"), size = 0.2) +
  geom_point(aes(y = yT3, color = "T3"), size = 0.2) +
  geom_point(aes(y = yT2, color = "T2"), size = 0.2) +
  labs(title = sprintf("Original Data\nFrom %s to %s", head(df$time,1), tail(df$time,1)), color = 'Probes') +
  ylab("Temperature [ceisius]") + 
  theme_minimal() + 
  theme_bw(base_size=base_size) # +
  # coord_cartesian(xlim = x_lim)
}
# Create q_circ plot
pqc <- ggplot(df) +
  geom_point(aes(y = q_circ, x = time), size = 0.2) + 
  ylab("q_circ [m^3/s]") + 
  theme_bw(base_size=base_size)#+ 
  # coord_cartesian(xlim = x_lim, ylim = y_lim)

# Create q_des plot
pqd <- ggplot(df) +
  geom_point(aes(y = q_des, x = time), size = 0.2) + 
  ylab("q_des [m^3/s]") + 
  theme_bw(base_size=base_size) #+ 
  # coord_cartesian(xlim = x_lim, ylim = y_lim)


if ("fixed_mu" == model_name){
  model_name <- "fixed_mu"
  model <- model_fixed_mu()
  model_fit_and_predict(model, df, name)
}
if ("fixed_mu_yT1" == model_name){
  model_name <- "fixed_mu_yT1"
  model <- model_fixed_mu_yT1()
  model_fit_and_predict(model, df, name)
}
if ("dynamic_mu" == model_name){
  model_name <- "dynamic_mu"
  model <- model_dynamic_mu()
  model_fit_and_predict(model, df, name)
}
if ("dynamic_mu_no_k4_sigma_x4" == model_name){
  model_name <- "dynamic_mu_no_k4_sigma_x4"
  model <- model_dynamic_mu_no_k4_sigma_x4()
  model_fit_and_predict(model, df, name)
}
if ("dynamic_mu_no_P_loss" == model_name){
  model_name <- "dynamic_mu_no_P_loss"
  model <- model_dynamic_mu_no_P_loss()
  model_fit_and_predict(model, df, name)
}
if ("dynamic_mu_no_k4_sigma_x4_P_loss" == model_name){
  model_name <- "dynamic_mu_no_k4_sigma_x4_P_loss"
  model <- model_dynamic_mu_no_k4_sigma_x4_P_loss()
  model_fit_and_predict(model, df, name)
}
if ("dynamic_mu_yT1" == model_name){
  model_name <- "dynamic_mu_yT1"
  model <- model_dynamic_mu_yT1()
  model_fit_and_predict(model, df, name)
}

sink(file = output_file, append = T)
print("END!")
sink(file = NULL)

}
validation_table <- data.frame(nll = ls_nll, df = ls_df, AIC = ls_AIC, RMSE = ls_RMSE, row.names = model_names)
validation_table

sink(file = sprintf("%s/%s validation_table.txt", Rfolder, name))
print(validation_table)
sink(file = NULL)
}
```

```{r}
df <- load_data("June short")
model_name <- "fixed_mu"
model <- model_fixed_mu()
sink(file = sprintf("%s/ctsm %s model.txt", Rfolder, model_name))
print(model)
sink(file = NULL)

model_name <- "fixed_mu_yT1"
model <- model_fixed_mu_yT1()
sink(file = sprintf("%s/ctsm %s model.txt", Rfolder, model_name))
print(model)
sink(file = NULL)

model_name <- "dynamic_mu"
model <- model_dynamic_mu()
sink(file = sprintf("%s/ctsm %s model.txt", Rfolder, model_name))
print(model)
sink(file = NULL)

model_name <- "dynamic_mu_no_k4_sigma_x4"
model <- model_dynamic_mu_no_k4_sigma_x4()
sink(file = sprintf("%s/ctsm %s model.txt", Rfolder, model_name))
print(model)
sink(file = NULL)
print(model)

model_name <- "dynamic_mu_no_P_loss"
model <- model_dynamic_mu_no_P_loss()
sink(file = sprintf("%s/ctsm %s model.txt", Rfolder, model_name))
print(model)
sink(file = NULL)

model_name <- "dynamic_mu_no_k4_sigma_x4_P_loss"
model <- model_dynamic_mu_no_k4_sigma_x4_P_loss()
sink(file = sprintf("%s/ctsm %s model.txt", Rfolder, model_name))
print(model)
sink(file = NULL)

model_name <- "dynamic_mu_yT1"
model <- model_dynamic_mu_yT1()
sink(file = sprintf("%s/ctsm %s model.txt", Rfolder, model_name))
print(model)
sink(file = NULL)
```